#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.xamarin.sample.splashscreen.Resource", IsApplication=true)]

namespace com.xamarin.sample.splashscreen
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int buttonColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int buttonRaised = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int leading = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int primaryButtonText = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int secondaryButtonText = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int select_dialog_multichoice = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int select_dialog_singlechoice = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int stackedMargin = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070006
			public const int accent = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int color_picker_background_color = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int color_picker_border_color = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int dropdown_dark_divider_color = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int dropdown_divider_color = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int primary = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int primaryDark = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int splash_background = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int window_background = 2131165191;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080002
			public const int color_button_height = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int color_picker_gradient_margin = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int config_min_scaling_span = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int dropdown_item_divider_height = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int dropdown_item_height = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int keyboard_accessory_chip_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int keyboard_accessory_half_padding = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int keyboard_accessory_height = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int keyboard_accessory_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int keyboard_accessory_text_size = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int link_preview_overlay_radius = 2131230720;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int autofill_chip_inset = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubble = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bubble_arrow_up = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_borderless_compat = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_compat = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_compat_shape = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int color_button_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int color_picker_advanced_select_handle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int color_picker_border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dropdown_label_color = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dropdown_popup_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dropdown_popup_background_down = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dropdown_popup_background_up = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_menu_share_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_search = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_warning = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ondemand_overlay = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash_logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int splash_screen = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int verify_checkmark = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001e
			public const int ampm = 2131296286;
			
			// aapt resource value: 0x7f090025
			public const int arrow_image = 2131296293;
			
			// aapt resource value: 0x7f090002
			public const int autofill_keyboard_accessory_item_label = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int autofill_keyboard_accessory_item_sublabel = 2131296259;
			
			// aapt resource value: 0x7f090029
			public const int color_button_swatch = 2131296297;
			
			// aapt resource value: 0x7f090008
			public const int color_picker_advanced = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int color_picker_simple = 2131296265;
			
			// aapt resource value: 0x7f09000f
			public const int date_picker = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int date_time_suggestion = 2131296273;
			
			// aapt resource value: 0x7f090013
			public const int date_time_suggestion_label = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int date_time_suggestion_value = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int download_service_notification = 2131296256;
			
			// aapt resource value: 0x7f090017
			public const int dropdown_icon = 2131296279;
			
			// aapt resource value: 0x7f090015
			public const int dropdown_label = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int dropdown_label_wrapper = 2131296276;
			
			// aapt resource value: 0x7f090001
			public const int dropdown_popup_window = 2131296257;
			
			// aapt resource value: 0x7f090016
			public const int dropdown_sublabel = 2131296278;
			
			// aapt resource value: 0x7f090006
			public const int gradient = 2131296262;
			
			// aapt resource value: 0x7f090005
			public const int gradient_border = 2131296261;
			
			// aapt resource value: 0x7f090018
			public const int hour = 2131296280;
			
			// aapt resource value: 0x7f090023
			public const int icon_view = 2131296291;
			
			// aapt resource value: 0x7f090026
			public const int main_text = 2131296294;
			
			// aapt resource value: 0x7f09001d
			public const int milli = 2131296285;
			
			// aapt resource value: 0x7f090019
			public const int minute = 2131296281;
			
			// aapt resource value: 0x7f09000b
			public const int more_colors_button = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int more_colors_button_border = 2131296266;
			
			// aapt resource value: 0x7f09001f
			public const int pickers = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int position_in_year = 2131296288;
			
			// aapt resource value: 0x7f09001b
			public const int second = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int second_colon = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int second_dot = 2131296284;
			
			// aapt resource value: 0x7f090007
			public const int seek_bar = 2131296263;
			
			// aapt resource value: 0x7f09002b
			public const int select_action_menu_copy = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int select_action_menu_cut = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int select_action_menu_paste = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int select_action_menu_select_all = 2131296302;
			
			// aapt resource value: 0x7f09002d
			public const int select_action_menu_share = 2131296301;
			
			// aapt resource value: 0x7f09002f
			public const int select_action_menu_text_processing_menus = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int select_action_menu_web_search = 2131296304;
			
			// aapt resource value: 0x7f09000e
			public const int selected_color_view = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int selected_color_view_border = 2131296269;
			
			// aapt resource value: 0x7f090027
			public const int sub_text = 2131296295;
			
			// aapt resource value: 0x7f090004
			public const int text = 2131296260;
			
			// aapt resource value: 0x7f090024
			public const int text_wrapper = 2131296292;
			
			// aapt resource value: 0x7f090010
			public const int time_picker = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int title = 2131296268;
			
			// aapt resource value: 0x7f090022
			public const int top_view = 2131296290;
			
			// aapt resource value: 0x7f090028
			public const int xwalkview = 2131296296;
			
			// aapt resource value: 0x7f090021
			public const int year = 2131296289;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int autofill_keyboard_accessory_icon = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int autofill_keyboard_accessory_item = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int color_picker_advanced_component = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int color_picker_dialog_content = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int color_picker_dialog_title = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int date_time_picker_dialog = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int date_time_suggestion = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int dropdown_item = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Main = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int multi_field_time_picker_dialog = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int two_field_date_picker = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int validation_message_bubble = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int Webview = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int XWalkView = 2130968589;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int select_action_menu = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int empty = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int launch_screen_api = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int wifidirect_api = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06005e
			public const int ApplicationName = 2131099742;
			
			// aapt resource value: 0x7f06005d
			public const int Hello = 2131099741;
			
			// aapt resource value: 0x7f06001e
			public const int accessibility_date_picker_month = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int accessibility_date_picker_week = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int accessibility_date_picker_year = 2131099679;
			
			// aapt resource value: 0x7f060030
			public const int accessibility_datetime_picker_date = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int accessibility_datetime_picker_time = 2131099697;
			
			// aapt resource value: 0x7f06002b
			public const int accessibility_time_picker_ampm = 2131099691;
			
			// aapt resource value: 0x7f060027
			public const int accessibility_time_picker_hour = 2131099687;
			
			// aapt resource value: 0x7f06002a
			public const int accessibility_time_picker_milli = 2131099690;
			
			// aapt resource value: 0x7f060028
			public const int accessibility_time_picker_minute = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int accessibility_time_picker_second = 2131099689;
			
			// aapt resource value: 0x7f060000
			public const int actionbar_share = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_textselection_title = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int actionbar_web_search = 2131099649;
			
			// aapt resource value: 0x7f060037
			public const int autofill_keyboard_accessory_content_description = 2131099703;
			
			// aapt resource value: 0x7f060035
			public const int autofill_popup_content_description = 2131099701;
			
			// aapt resource value: 0x7f06001b
			public const int color_picker_button_black = 2131099675;
			
			// aapt resource value: 0x7f060017
			public const int color_picker_button_blue = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int color_picker_button_cancel = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int color_picker_button_cyan = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int color_picker_button_green = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int color_picker_button_magenta = 2131099673;
			
			// aapt resource value: 0x7f06000e
			public const int color_picker_button_more = 2131099662;
			
			// aapt resource value: 0x7f060015
			public const int color_picker_button_red = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int color_picker_button_set = 2131099666;
			
			// aapt resource value: 0x7f06001c
			public const int color_picker_button_white = 2131099676;
			
			// aapt resource value: 0x7f06001a
			public const int color_picker_button_yellow = 2131099674;
			
			// aapt resource value: 0x7f060014
			public const int color_picker_dialog_title = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int color_picker_hue = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int color_picker_saturation = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int color_picker_value = 2131099665;
			
			// aapt resource value: 0x7f06001d
			public const int copy_to_clipboard_failure_message = 2131099677;
			
			// aapt resource value: 0x7f060051
			public const int crosswalk_install_title = 2131099729;
			
			// aapt resource value: 0x7f060034
			public const int date_picker_dialog_clear = 2131099700;
			
			// aapt resource value: 0x7f060032
			public const int date_picker_dialog_other_button_label = 2131099698;
			
			// aapt resource value: 0x7f060020
			public const int date_picker_dialog_set = 2131099680;
			
			// aapt resource value: 0x7f060033
			public const int date_picker_dialog_title = 2131099699;
			
			// aapt resource value: 0x7f06002f
			public const int date_time_picker_dialog_title = 2131099695;
			
			// aapt resource value: 0x7f060053
			public const int decompression_progress_message = 2131099731;
			
			// aapt resource value: 0x7f06003e
			public const int download_already_exists_toast = 2131099710;
			
			// aapt resource value: 0x7f060052
			public const int download_failed_message = 2131099730;
			
			// aapt resource value: 0x7f06003f
			public const int download_failed_toast = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int download_finished_toast = 2131099712;
			
			// aapt resource value: 0x7f06003d
			public const int download_no_permission_toast = 2131099709;
			
			// aapt resource value: 0x7f060054
			public const int download_progress_message = 2131099732;
			
			// aapt resource value: 0x7f06003c
			public const int download_start_toast = 2131099708;
			
			// aapt resource value: 0x7f060057
			public const int google_play_store = 2131099735;
			
			// aapt resource value: 0x7f060045
			public const int http_auth_log_in = 2131099717;
			
			// aapt resource value: 0x7f060044
			public const int http_auth_password = 2131099716;
			
			// aapt resource value: 0x7f060042
			public const int http_auth_title = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int http_auth_user_name = 2131099715;
			
			// aapt resource value: 0x7f060039
			public const int js_alert_title = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int js_confirm_title = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int js_prompt_title = 2131099707;
			
			// aapt resource value: 0x7f06000c
			public const int low_memory_error = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int media_player_error_button = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int media_player_error_text_invalid_progressive_playback = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int media_player_error_text_unknown = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int media_player_error_title = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int media_player_loading_video = 2131099655;
			
			// aapt resource value: 0x7f060021
			public const int month_picker_dialog_title = 2131099681;
			
			// aapt resource value: 0x7f06000d
			public const int opening_file_error = 2131099661;
			
			// aapt resource value: 0x7f060036
			public const int password_generation_popup_content_description = 2131099702;
			
			// aapt resource value: 0x7f06000b
			public const int profiler_error_toast = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int profiler_no_storage_toast = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int profiler_started_toast = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int profiler_stopped_toast = 2131099657;
			
			// aapt resource value: 0x7f060055
			public const int select_store_message = 2131099733;
			
			// aapt resource value: 0x7f060041
			public const int ssl_alert_title = 2131099713;
			
			// aapt resource value: 0x7f060046
			public const int ssl_error_deny_request = 2131099718;
			
			// aapt resource value: 0x7f06004e
			public const int startup_architecture_mismatch_message = 2131099726;
			
			// aapt resource value: 0x7f06004d
			public const int startup_architecture_mismatch_title = 2131099725;
			
			// aapt resource value: 0x7f06004c
			public const int startup_newer_version_message = 2131099724;
			
			// aapt resource value: 0x7f06004b
			public const int startup_newer_version_title = 2131099723;
			
			// aapt resource value: 0x7f060048
			public const int startup_not_found_message = 2131099720;
			
			// aapt resource value: 0x7f060047
			public const int startup_not_found_title = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int startup_older_version_message = 2131099722;
			
			// aapt resource value: 0x7f060049
			public const int startup_older_version_title = 2131099721;
			
			// aapt resource value: 0x7f060050
			public const int startup_signature_check_error_message = 2131099728;
			
			// aapt resource value: 0x7f06004f
			public const int startup_signature_check_error_title = 2131099727;
			
			// aapt resource value: 0x7f060024
			public const int time_picker_dialog_am = 2131099684;
			
			// aapt resource value: 0x7f06002c
			public const int time_picker_dialog_hour_minute_separator = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int time_picker_dialog_minute_second_separator = 2131099693;
			
			// aapt resource value: 0x7f060025
			public const int time_picker_dialog_pm = 2131099685;
			
			// aapt resource value: 0x7f06002e
			public const int time_picker_dialog_second_subsecond_separator = 2131099694;
			
			// aapt resource value: 0x7f060026
			public const int time_picker_dialog_title = 2131099686;
			
			// aapt resource value: 0x7f060056
			public const int unsupported_store_message = 2131099734;
			
			// aapt resource value: 0x7f060038
			public const int updating_chrome = 2131099704;
			
			// aapt resource value: 0x7f060023
			public const int week_picker_dialog_title = 2131099683;
			
			// aapt resource value: 0x7f060059
			public const int xwalk_cancel = 2131099737;
			
			// aapt resource value: 0x7f06005b
			public const int xwalk_close = 2131099739;
			
			// aapt resource value: 0x7f06005a
			public const int xwalk_continue = 2131099738;
			
			// aapt resource value: 0x7f060058
			public const int xwalk_get_crosswalk = 2131099736;
			
			// aapt resource value: 0x7f06005c
			public const int xwalk_retry = 2131099740;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0007
			public const int ButtonCompat = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int ButtonCompatBase = 2131361798;
			
			// aapt resource value: 0x7f0a0008
			public const int ButtonCompatBorderless = 2131361800;
			
			// aapt resource value: 0x7f0a0005
			public const int ButtonCompatBorderlessOverlay = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int ButtonCompatOverlay = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int DropdownPopupWindow = 2131361795;
			
			// aapt resource value: 0x7f0a000a
			public const int MyTheme = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int MyTheme_Base = 2131361801;
			
			// aapt resource value: 0x7f0a000b
			public const int MyTheme_Splash = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int SelectActionMenuShare = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int SelectActionMenuWebSearch = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int SelectPopupDialog = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonCompat = new int[] {
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int ButtonCompat_buttonColor = 0;
			
			// aapt resource value: 1
			public const int ButtonCompat_buttonRaised = 1;
			
			public static int[] DualControlLayout = new int[] {
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int DualControlLayout_primaryButtonText = 1;
			
			// aapt resource value: 2
			public const int DualControlLayout_secondaryButtonText = 2;
			
			// aapt resource value: 0
			public const int DualControlLayout_stackedMargin = 0;
			
			public static int[] TextViewWithLeading = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int TextViewWithLeading_leading = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
